#!/bin/bash

# declare parameter list array
PARAMETERS=()

# read arguments
# help:
# help: Usage: %scriptname% [options...]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        # help:
        -h|--help)
            cat "$pathRoot/lib/parameter" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | sed "s~%scriptname%~$scriptname~g"
            setCachedValue "$INI_FILE" scriptIsRunning false
            exit 0
            ;;

        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

